### PR TITLE
Add aphrodite

### PR DESCRIPTION
**Pull request by xymostech**
Summary: Adds aphrodite (and it's snazzy logo from Elizabeth Lin!) to
the KA open source page.

Feedback wanted on the description. Suggestions: "CSS for Robots"

Test Plan:
 - Run a web server in this directory
 - Visit the page, see that Aphrodite shows up
 - Scroll to the bottom, see that all of the rows look fine.

image

@jdan

### CODE REVIEW

**Comment by jdan** [comment]
LGTM! Might want to remove another repo from the page to get two nice columns.

Also I'll continue pushing for "CSS for robots" but it's your library after all :)

**Comment by xymostech** [comment]
nixed khan-exercises. :wave:

**Comment by k4b7** [comment]
Cool logo!

**Comment by jlfwong** [comment]
Ooo, I like the logo :D

**Pull request merged**
