### PR TITLE
redirect khan.github.io/KaTeX to katex.org

### PR DESCRIPTION
**Pull request by k4b7**
In anticipation of moving the KaTeX repo to the KaTeX organization, this PR redirects khan.github.io/KaTeX to katex.org.  We added redirects in https://github.com/Khan/KaTeX/pull/1685, but those redirects will fail once we transfer the repo.

Test Plan:
To test this I visited https://deploy-preview-10--khan-github-io.netlify.com/KaTeX and saw that it redirected to https://katex.org.

TODOs:
- [x] copy the folder structure in https://github.com/Khan/KaTeX/pull/1685 so that we can redirect from all the existing documentation pages.

cc @ylemkimon @edemaine @sophiebits

### CODE REVIEW

**Comment by k4b7** [comment]
I think we should be able to use `jekyll-redirect-from` here as well and then we can just copy the file from https://github.com/Khan/KaTeX/tree/gh-pages into the `KaTeX` folder in this repo.

**Comment by k4b7** [comment]
To test this I loaded https://deploy-preview-10--khan-github-io.netlify.com/KaTeX/docs/api.html and saw that it redirected to https://katex.org/docs/api.html.

**Comment by edemaine** [comment]
Awesome! This looks good to me, but it would be good to get @ylemkimon's review.

**Comment by ylemkimon** [comment]
I wonder what happens if the name of a subdirectory and the name of a repo with GitHub Pages conflict.

**Comment by k4b7** [comment]
@ylemkimon I'm not sure which one wins.  We'll find out once this lands, but this situation should be short-lived since the plan is to switch ownership of the `KaTeX` repo shortly thereafter.

**Review by jeresig — APPROVED** [review]
Looks good!

**Pull request merged**
