### PR TITLE
Add genqlient

### PR DESCRIPTION
**Pull request by benjaminjkraft**
## Summary:
We're getting close to ready to make genqlient "maintained open-source"!
So it's time to add it here.  In general I think this page needs some
reordering but I just put it in at a seemingly reasonable place to
start.  The header image from its README doesn't really work well at
this size, so I just left it without a logo for now; we can add one
when someone gets a chance to make one.

I'll hold off on landing this until genqlient#96 lands.

Issue: https://github.com/Khan/genqlient/issues/35

## Test plan:
`npm run build` and view in a browser

### CODE REVIEW

**Review by somewhatabstract — APPROVED** [review]
LGTM

**Review by k4b7 — APPROVED** [review]
:shipit:

**Comment by benjaminjkraft** [comment]
Whoops, I forgot to merge after Jeff approved this and now don't have permissions.  Could someone else land it?

**Comment by somewhatabstract** [comment]
> Whoops, I forgot to merge after Jeff approved this and now don't have permissions. Could someone else land it?

Sure :)

**Pull request merged**
