### PR TITLE
Replace logo

### PR DESCRIPTION
**Pull request by somewhatabstract**
This updates the logo that appears at the top of the page to use our new logo! Yay!

### CODE REVIEW

**Comment by benjaminjkraft** [comment]
Looks like the new one is a different size, does it still show up correctly and fit well on the page?

**Comment by somewhatabstract** [comment]
Yeah, just updated to fix that. Here's a screen grab.

screen shot 2018-08-08 at 1 56 18 pm

**Review by benjaminjkraft — APPROVED** [review]
The sizing doesn't seem ideal right next to the larger "OPEN SOURCE" text, but it's no worse than the existing logo, so we can just fix that separately.  Thanks for the super quick fix!

**Comment by somewhatabstract** [comment]
Yeah, totally agree.

I'll be making some changes to get this more Wonder Blocks-aligned (and also include Wonder Blocks in the list?) at some point soon. We can fix that up then.

**Pull request merged**
